name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give Execute Permission
        run: chmod +x mvnw

      - name: Build Project
        run: ./mvnw clean install

      - name: Run Tests
        run: ./mvnw test